#!/usr/bin/env bash
if [ "$2" == "clone" ]; then
  git clone git@github.com:Snooking/PythonAnalyticsForRebis.git $1 && cd $1;
fi

git config --global core.autocrlf false
git config --global core.eol LF
git config --global core.fileMode false
git config --global diff.renamelimit 5000

sudo chmod -R u+x ./*

chmod -R 777 src

bash start